import { useEffect, useMemo, useState } from "react";
import { useLocation, useParams } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { getLoginUrl } from "@/const";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowLeft, BadgeDollarSign, Box, CalendarRange, ChevronDown, DollarSign, Download, Loader2, MousePointerClick, RefreshCw, ShoppingCart, Star, TrendingDown, TrendingUp, Users } from "lucide-react";
import { downloadProductAnalysisWorkbook } from "@/lib/productAnalysisExcelExport";

type Status = "star" | "loss" | "attention" | "normal";
type Product = { asin: string; sku: string; ownerName: string; title: string; units: number; sales: number; orders: number; grossProfit: number | null; profitMargin: number | null; adSpend: number; adOrders: number; adRate: number | null; adOrderShare: number | null; averageOrderValue: number | null; cpc: number | null; salesGrade: string; status: Status; statusReason: string; suggestion: string; unitsChange: number | null; salesChange: number | null; adSpendChange: number | null; profitChange: number | null };
type Result = { summary: { totalProducts: number; totalUnits: number; totalSales: number; totalAdSpend: number; totalGrossProfit: number | null; adRate: number | null; adOrderShare: number | null; averageOrderValue: number | null; cpc: number | null; profitMargin: number | null; hasProfitData: boolean; gradeCounts: Record<string, number>; statusCounts: Record<Status, number> }; ownerSummaries: Array<{ ownerName: string; productCount: number; units: number; sales: number; adSpend: number; grossProfit: number | null; adRate: number | null; profitMargin: number | null; starCount: number; lossCount: number; attentionCount: number }>; products: Product[]; currentPeriod: string | null; priorPeriod: string | null };

const STATUS = { star: { label: "明星", color: "#34d399", chip: "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" }, loss: { label: "亏损", color: "#f87171", chip: "border-rose-400/30 bg-rose-400/10 text-rose-300" }, attention: { label: "注意", color: "#fbbf24", chip: "border-amber-400/30 bg-amber-400/10 text-amber-300" }, normal: { label: "正常", color: "#94a3b8", chip: "border-slate-400/30 bg-slate-400/10 text-slate-300" } } as const;
const GRADE_COLORS = ["#22d3ee", "#38bdf8", "#818cf8", "#a78bfa", "#fbbf24", "#fb923c", "#f97316", "#64748b"];
const money = (value: number | null | undefined) => value === null || value === undefined ? "—" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const percent = (value: number | null | undefined) => value === null || value === undefined ? "—" : `${(value * 100).toFixed(1)}%`;
const delta = (value: number | null | undefined) => value === null || value === undefined ? "—" : `${value >= 0 ? "+" : ""}${(value * 100).toFixed(1)}%`;

function MetricCard({ label, value, note, icon: Icon, tone = "cyan" }: { label: string; value: string; note: string; icon: typeof DollarSign; tone?: "cyan" | "emerald" | "violet" | "amber" }) {
  const tones = { cyan: "text-cyan-300 bg-cyan-400/10", emerald: "text-emerald-300 bg-emerald-400/10", violet: "text-violet-300 bg-violet-400/10", amber: "text-amber-300 bg-amber-400/10" };
  return <div className="rounded-2xl border border-border/60 bg-card/70 p-5 shadow-sm"><div className="flex items-start justify-between"><span className="text-sm text-muted-foreground">{label}</span><span className={`rounded-lg p-2 ${tones[tone]}`}><Icon className="h-4 w-4" /></span></div><p className="mt-4 text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>;
}

function RankingCard({ title, icon: Icon, rows, status }: { title: string; icon: typeof Star; rows: Product[]; status: Status }) {
  return <div className="rounded-2xl border border-border/60 bg-card/70 p-5"><div className="mb-4 flex items-center gap-2"><Icon className="h-4 w-4" style={{ color: STATUS[status].color }} /><h3 className="font-semibold">{title}</h3><span className="text-xs text-muted-foreground">Top 5</span></div>{rows.length ? <div className="space-y-3">{rows.map((row, index) => <div key={`${row.asin}-${index}`} className="flex items-center gap-3"><span className="w-5 text-xs text-muted-foreground">{index + 1}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{row.asin || row.sku}</p><p className="truncate text-xs text-muted-foreground">{row.ownerName} · {row.statusReason}</p></div><p className="text-sm font-semibold">{money(row.sales)}</p></div>)}</div> : <p className="py-7 text-center text-sm text-muted-foreground">暂无符合条件的产品</p>}</div>;
}

export default function ProductAnalysis() {
  const { taskId } = useParams<{ taskId: string }>();
  const id = Number(taskId);
  const { isAuthenticated, loading } = useAuth();
  const [, navigate] = useLocation();
  const [owner, setOwner] = useState("ALL");
  const taskQuery = trpc.productAnalysis.getTask.useQuery({ taskId: id }, { enabled: Number.isFinite(id) && isAuthenticated });
  const resultQuery = trpc.productAnalysis.getResult.useQuery({ taskId: id }, { enabled: Number.isFinite(id) && isAuthenticated, refetchInterval: (query) => query.state.data?.status === "completed" ? false : 2500 });
  const result = resultQuery.data?.result as unknown as Result | undefined;

  useEffect(() => { if (!loading && !isAuthenticated) window.location.href = getLoginUrl(); }, [loading, isAuthenticated]);
  const owners = useMemo(() => result?.ownerSummaries.map((item) => item.ownerName) ?? [], [result]);
  const products = useMemo(() => result?.products.filter((item) => owner === "ALL" || item.ownerName === owner) ?? [], [result, owner]);
  const summary = useMemo(() => {
    if (!result) return null;
    if (owner === "ALL") return result.summary;
    const sum = (key: keyof Product) => products.reduce((total, item) => total + (typeof item[key] === "number" ? Number(item[key]) : 0), 0);
    const sales = sum("sales"), orders = sum("orders"), spend = sum("adSpend"), clicks = products.reduce((total, item) => total + (item.cpc ? item.adSpend / item.cpc : 0), 0);
    const profitRows = products.filter((item) => item.grossProfit !== null); const grossProfit = profitRows.length ? profitRows.reduce((total, item) => total + (item.grossProfit ?? 0), 0) : null;
    return { ...result.summary, totalProducts: products.length, totalUnits: sum("units"), totalSales: sales, totalAdSpend: spend, totalGrossProfit: grossProfit, adRate: sales ? spend / sales : null, adOrderShare: orders ? sum("adOrders") / orders : null, averageOrderValue: orders ? sales / orders : null, cpc: clicks ? spend / clicks : null, profitMargin: grossProfit !== null && sales ? grossProfit / sales : null, statusCounts: { star: products.filter((item) => item.status === "star").length, loss: products.filter((item) => item.status === "loss").length, attention: products.filter((item) => item.status === "attention").length, normal: products.filter((item) => item.status === "normal").length } };
  }, [result, owner, products]);
  const gradeData = useMemo(() => ["S", "A", "B", "C", "D", "E", "F", "X"].map((grade) => ({ grade, count: products.filter((item) => item.salesGrade === grade).length })), [products]);
  const rankings = useMemo(() => ({ star: products.filter((item) => item.status === "star").sort((a, b) => b.sales - a.sales).slice(0, 5), loss: products.filter((item) => item.status === "loss").sort((a, b) => (a.grossProfit ?? 0) - (b.grossProfit ?? 0)).slice(0, 5), attention: products.filter((item) => item.status === "attention").sort((a, b) => (b.adRate ?? 0) - (a.adRate ?? 0)).slice(0, 5) }), [products]);

  if (loading || !isAuthenticated || taskQuery.isLoading || resultQuery.isLoading) return <div className="grid min-h-screen place-items-center bg-background"><Loader2 className="h-7 w-7 animate-spin text-primary" /></div>;
  if (!result || !summary) return <div className="grid min-h-screen place-items-center bg-background text-center"><div><Loader2 className="mx-auto h-7 w-7 animate-spin text-primary" /><p className="mt-3 text-sm text-muted-foreground">正在解析产品表现报告…</p><Button className="mt-5" variant="outline" onClick={() => resultQuery.refetch()}>刷新状态</Button></div></div>;

  return <div className="min-h-screen bg-background text-foreground"><nav className="sticky top-0 z-30 border-b border-border/50 bg-background/90 backdrop-blur-xl"><div className="container flex h-16 items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><Button variant="ghost" size="sm" onClick={() => navigate("/")}><ArrowLeft className="mr-1 h-4 w-4" />返回</Button><span className="hidden h-4 w-px bg-border sm:block" /><div className="min-w-0"><p className="truncate text-sm font-semibold">产品表现分析</p><p className="text-xs text-muted-foreground">{result.priorPeriod ? `${result.priorPeriod} → ${result.currentPeriod}` : result.currentPeriod ?? "当前周期"}</p></div></div><div className="flex items-center gap-2"><div className="relative"><select value={owner} onChange={(event) => setOwner(event.target.value)} className="h-9 appearance-none rounded-lg border border-border bg-card py-0 pl-3 pr-8 text-sm outline-none"><option value="ALL">全部负责人</option>{owners.map((name) => <option key={name} value={name}>{name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2.5 top-2.5 h-4 w-4 text-muted-foreground" /></div><Button size="sm" variant="outline" onClick={() => downloadProductAnalysisWorkbook(result as unknown as Record<string, unknown>, taskQuery.data?.task.name ?? "产品表现分析", owner)}><Download className="mr-1 h-4 w-4" />导出Excel</Button><Button size="sm" variant="outline" onClick={() => resultQuery.refetch()}><RefreshCw className="mr-1 h-4 w-4" />刷新</Button><Button size="sm" onClick={() => navigate("/product-analysis/upload")}>新建分析</Button></div></div></nav>
    <main className="container py-7"><div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><div className="mb-2 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs text-primary"><CalendarRange className="h-3.5 w-3.5" />独立产品经营看板</div><h1 className="text-2xl font-bold">{owner === "ALL" ? "全店产品表现总览" : `${owner} 的产品表现`}</h1></div><span className="text-xs text-muted-foreground">产品数 {summary.totalProducts} · {summary.hasProfitData ? "已接入利润数据" : "未接入利润数据"}</span></div>
      <section className="grid grid-cols-2 gap-3 lg:grid-cols-4 xl:grid-cols-7"><MetricCard label="业绩销量" value={summary.totalUnits.toLocaleString()} note="本期总销量" icon={ShoppingCart} /><MetricCard label="销售额" value={money(summary.totalSales)} note="本期总业绩" icon={TrendingUp} tone="emerald" /><MetricCard label="广告费" value={money(summary.totalAdSpend)} note={`费率 ${percent(summary.adRate)}`} icon={BadgeDollarSign} tone="violet" /><MetricCard label="广告单占比" value={percent(summary.adOrderShare)} note="广告订单 / 总订单" icon={Box} tone="amber" /><MetricCard label="客单价" value={money(summary.averageOrderValue)} note="销售额 / 订单量" icon={DollarSign} /><MetricCard label="CPC" value={money(summary.cpc)} note="广告花费 / 点击" icon={MousePointerClick} tone="violet" /><MetricCard label="结算毛利" value={money(summary.totalGrossProfit)} note={`毛利率 ${percent(summary.profitMargin)}`} icon={BadgeDollarSign} tone="emerald" /></section>
      {!summary.hasProfitData && <div className="mt-5 flex gap-2 rounded-xl border border-amber-400/30 bg-amber-400/5 p-3 text-xs text-amber-200"><AlertTriangle className="h-4 w-4 shrink-0" />未找到结算毛利润/毛利率字段，亏损榜仅能按高广告费率与低销量提示。请上传包含利润字段的领星产品表现报告。</div>}
      <section className="mt-5 grid gap-5 xl:grid-cols-[1.15fr_0.85fr]"><div className="rounded-2xl border border-border/60 bg-card/70 p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">产品销量等级</h2><p className="mt-1 text-xs text-muted-foreground">S &gt;150 · A 100–150 · B 70–100 · C 50–70 · D 35–50 · E 20–35 · F 10–20 · X &lt;10</p></div></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={gradeData}><CartesianGrid vertical={false} stroke="#334155" strokeDasharray="3 3" /><XAxis dataKey="grade" tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fill: "#94a3b8", fontSize: 12 }} /><Tooltip contentStyle={{ background: "#0f172a", border: "1px solid #334155", borderRadius: 10 }} formatter={(value: number) => [value, "产品数"]} /><Bar dataKey="count" radius={[6, 6, 0, 0]}>{gradeData.map((entry, index) => <Cell key={entry.grade} fill={GRADE_COLORS[index]} />)}</Bar></BarChart></ResponsiveContainer></div></div><div className="rounded-2xl border border-border/60 bg-card/70 p-5"><div className="mb-4 flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-300" /><h2 className="font-semibold">产品健康分布</h2></div><div className="space-y-4">{(["star", "loss", "attention", "normal"] as Status[]).map((status) => { const count = summary.statusCounts[status]; const share = summary.totalProducts ? count / summary.totalProducts * 100 : 0; return <div key={status}><div className="mb-1.5 flex justify-between text-sm"><span style={{ color: STATUS[status].color }}>{STATUS[status].label}</span><span className="text-muted-foreground">{count} 个 · {share.toFixed(0)}%</span></div><div className="h-2 rounded-full bg-muted"><div className="h-full rounded-full" style={{ width: `${share}%`, backgroundColor: STATUS[status].color }} /></div></div>; })}</div></div></section>
      <section className="mt-5 grid gap-5 xl:grid-cols-3"><RankingCard title="明星榜" icon={Star} rows={rankings.star} status="star" /><RankingCard title="亏损榜" icon={TrendingDown} rows={rankings.loss} status="loss" /><RankingCard title="注意榜" icon={AlertTriangle} rows={rankings.attention} status="attention" /></section>
      <section className="mt-5 rounded-2xl border border-border/60 bg-card/70"><div className="flex items-center justify-between border-b border-border/60 px-5 py-4"><div><h2 className="font-semibold">人员经营维度</h2><p className="mt-1 text-xs text-muted-foreground">按负责人汇总产品数量、业绩、广告费率与风险产品</p></div><Users className="h-4 w-4 text-muted-foreground" /></div><div className="overflow-x-auto"><table className="w-full min-w-[880px] text-sm"><thead className="bg-muted/20 text-left text-xs text-muted-foreground"><tr><th className="px-5 py-3 font-medium">负责人</th><th className="px-3 py-3 text-right font-medium">产品数</th><th className="px-3 py-3 text-right font-medium">销量</th><th className="px-3 py-3 text-right font-medium">销售额</th><th className="px-3 py-3 text-right font-medium">广告费</th><th className="px-3 py-3 text-right font-medium">广告费率</th><th className="px-3 py-3 text-right font-medium">结算毛利率</th><th className="px-5 py-3 text-right font-medium">明星 / 亏损 / 注意</th></tr></thead><tbody>{result.ownerSummaries.map((item) => <tr key={item.ownerName} className="border-t border-border/40 transition hover:bg-muted/20"><td className="px-5 py-3 font-medium">{item.ownerName}</td><td className="px-3 py-3 text-right">{item.productCount}</td><td className="px-3 py-3 text-right">{item.units.toLocaleString()}</td><td className="px-3 py-3 text-right font-medium">{money(item.sales)}</td><td className="px-3 py-3 text-right">{money(item.adSpend)}</td><td className="px-3 py-3 text-right">{percent(item.adRate)}</td><td className="px-3 py-3 text-right">{percent(item.profitMargin)}</td><td className="px-5 py-3 text-right"><span className="text-emerald-300">{item.starCount}</span><span className="text-muted-foreground"> / </span><span className="text-rose-300">{item.lossCount}</span><span className="text-muted-foreground"> / </span><span className="text-amber-300">{item.attentionCount}</span></td></tr>)}</tbody></table></div></section>
      <section className="mt-5 rounded-2xl border border-border/60 bg-card/70"><div className="flex items-center justify-between border-b border-border/60 px-5 py-4"><div><h2 className="font-semibold">所有产品分析</h2><p className="mt-1 text-xs text-muted-foreground">按销售额排序 · {products.length} 个产品</p></div><Users className="h-4 w-4 text-muted-foreground" /></div><div className="max-h-[calc(100vh-270px)] overflow-auto"><table className="w-full min-w-[1320px] text-sm"><thead className="sticky top-0 z-10 bg-card/95 backdrop-blur"><tr className="border-b border-border/70 text-left text-xs text-muted-foreground"><th className="px-4 py-3 font-medium">ASIN / 产品</th><th className="px-3 py-3 font-medium">负责人</th><th className="px-3 py-3 text-right font-medium">销量等级</th><th className="px-3 py-3 text-right font-medium">销量</th><th className="px-3 py-3 text-right font-medium">销售额</th><th className="px-3 py-3 text-right font-medium">广告费</th><th className="px-3 py-3 text-right font-medium">费率</th><th className="px-3 py-3 text-right font-medium">广告单占比</th><th className="px-3 py-3 text-right font-medium">客单价</th><th className="px-3 py-3 text-right font-medium">CPC</th><th className="px-3 py-3 text-right font-medium">毛利率</th><th className="px-3 py-3 font-medium">诊断</th><th className="px-4 py-3 font-medium">环比销售额</th></tr></thead><tbody>{products.map((item) => <tr key={`${item.asin}-${item.sku}`} className="border-b border-border/40 transition hover:bg-muted/30"><td className="max-w-[240px] px-4 py-3"><p className="font-medium">{item.asin || item.sku}</p><p className="truncate text-xs text-muted-foreground">{item.title || item.sku}</p></td><td className="px-3 py-3">{item.ownerName}</td><td className="px-3 py-3 text-right"><span className="rounded-md border border-primary/25 bg-primary/10 px-2 py-1 text-xs font-bold text-primary">{item.salesGrade}</span></td><td className="px-3 py-3 text-right tabular-nums">{item.units.toLocaleString()}</td><td className="px-3 py-3 text-right tabular-nums font-medium">{money(item.sales)}</td><td className="px-3 py-3 text-right tabular-nums">{money(item.adSpend)}</td><td className="px-3 py-3 text-right tabular-nums">{percent(item.adRate)}</td><td className="px-3 py-3 text-right tabular-nums">{percent(item.adOrderShare)}</td><td className="px-3 py-3 text-right tabular-nums">{money(item.averageOrderValue)}</td><td className="px-3 py-3 text-right tabular-nums">{money(item.cpc)}</td><td className="px-3 py-3 text-right tabular-nums">{percent(item.profitMargin)}</td><td className="px-3 py-3"><span className={`rounded-full border px-2 py-1 text-xs ${STATUS[item.status].chip}`}>{STATUS[item.status].label}</span><p className="mt-1 max-w-[190px] truncate text-[11px] text-muted-foreground" title={item.statusReason}>{item.statusReason}</p></td><td className={`px-4 py-3 tabular-nums ${item.salesChange !== null && item.salesChange < 0 ? "text-rose-300" : "text-emerald-300"}`}>{delta(item.salesChange)}</td></tr>)}</tbody></table></div></section>
    </main></div>;
}
